In [1]:
import numpy as np
from sympy.physics.quantum import TensorProduct
from numpy import linalg as LA
from pylab import *

In [2]:
sigma_x=np.array([[0,1],[1,0]])
sigma_y=np.array([[0,1j],[1j,0]])
sigma_z=np.array([[1,0],[0,-1]])
sigma_0=np.array([[1,0],[0,1]])

In [3]:
def sigmaxyz_n(sig,i,n):
    sig_n=1
    for idx in range(n):
        if idx==i:
            sig_n=TensorProduct(sig,sig_n)
        else:
            sig_n=TensorProduct(sigma_0,sig_n)
    return sig_n

def Hij(i,j,n):
    H_ij=np.matmul(sigmaxyz_n(sigma_z,i,n),sigmaxyz_n(sigma_z,j,n))
    return H_ij

def Hamiltonian(n,h):
    H0=Hij(1,0,n)
    for i in range (1,n-1):
        H0=H0+Hij(i+1,i,n)
    H0=H0+Hij(0,n-1,n)
    Ht=H0
    for i in range(n):
        Ht=Ht+h*sigmaxyz_n(sigma_x,i,n)
    return -Ht

In [4]:
def minlist(list):
    n=list.shape[0]
    min=list[0]
    idx_min=0
    for idx in range(n):
        if (list[idx] < min):
            min=list[idx]
            idx_min=idx
    return min,idx_min

In [5]:
def groundsate(n,h):
    Ht=Hamiltonian(n,h)
    En, vec = LA.eig(Ht)
    En=np.real(En)
    Emin,idx_Emin=minlist(En)
    vec_Emin=vec[:,idx_Emin]
    return Emin, vec_Emin

In [6]:
n = int(input())

3


In [7]:
h=float(input())

2


In [8]:
print(Hamiltonian(n,h))

[[-3. -2. -2. -0. -2. -0. -0. -0.]
 [-2.  1. -0. -2. -0. -2. -0. -0.]
 [-2. -0.  1. -2. -0. -0. -2. -0.]
 [-0. -2. -2.  1. -0. -0. -0. -2.]
 [-2. -0. -0. -0.  1. -2. -2. -0.]
 [-0. -2. -0. -0. -2.  1. -0. -2.]
 [-0. -0. -2. -0. -2. -0.  1. -2.]
 [-0. -0. -0. -2. -0. -2. -2. -3.]]


In [9]:
Emin_exact,vec_Emin_exact=groundsate(n,h)
print(Emin_exact)
print(vec_Emin_exact)

-6.46410161513775
[0.5        0.28867513 0.28867513 0.28867513 0.28867513 0.28867513
 0.28867513 0.5       ]


In [10]:
# Tim teta_min

def alpha_Psi(i,j,Psi):
    if (i==0):
        alpha=Psi[j]
    else:
        a1=alpha_Psi(i-1,2*j+1,Psi)
        a0=alpha_Psi(i-1,2*j,Psi)
        alpha=np.sqrt(np.abs(a0)**2 + np.abs(a1)**2)*exp(1j*np.angle(a0))
    return alpha

def find_teta(i,j,Psi):
    a0=alpha_Psi(i,2*j,Psi)
    a1=alpha_Psi(i,2*j+1,Psi)
    
    if np.abs(a0)==0:
        teta=np.pi
    else:
        tan_teta=np.abs(a1)/np.abs(a0)
        teta=2*np.arctan(tan_teta)
    return teta

def find_phi(i,j,Psi):
    ai1j=alpha_Psi(i+1,j,Psi)
    ai2j1=alpha_Psi(i,2*j+1,Psi)
    phi=np.angle(ai2j1)-np.angle(ai1j)
    return phi

def teta(Psi):
    n=int(np.log2(np.max(Psi.shape)))
    teta=[]
    for i in range (n-1,-1,-1):
        jmax= 2**(n-i-1)
        for j in range (jmax):
            teta_ij=find_teta(i,j,Psi)
            teta.append(teta_ij)
    return teta
def phi(Psi):
    n=int(np.log2(np.max(Psi.shape)))
    phi=[]
    for i in range (n-1,-1,-1):
        jmax= 2**(n-i-1)
        for j in range (jmax):
            phi_ij=find_phi(i,j,Psi)
            phi.append(phi_ij)
    return phi

In [12]:
n = 3

In [16]:
h=float(input())

1.5


In [11]:
Emin_exact,vec_Emin_exact=groundsate(n,h)
print(Emin_exact/3)
print(vec_Emin_exact)

-2.15470053837925
[0.5        0.28867513 0.28867513 0.28867513 0.28867513 0.28867513
 0.28867513 0.5       ]


In [12]:
Psi=vec_Emin_exact
print(Psi)

[0.5        0.28867513 0.28867513 0.28867513 0.28867513 0.28867513
 0.28867513 0.5       ]


In [13]:
print(teta(Psi))

[1.5707963267948968, 1.2309594173407752, 1.9106332362490184, 1.0471975511965976, 1.5707963267948963, 1.5707963267948966, 2.094395102393195]


In [33]:
print(phi(Psi))

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
